name: 'CI'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage  

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/*.xml

      - name: Create test report
        uses: ./
        if: success() || failure()
        with:
          name: JEST Tests
          path: tests/*.xml
          reporter: jest-junit