name: Main CI GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  back-end-ci:
    name: Build, test and analyze Back
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'back'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: ./.github/workflows/composite-action

  build-image-docker:
    name: Build image Doker of backend and push to docker hub
    runs-on: ubuntu-latest
    needs: back-end-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/bobapp:latest


  front-ci:
    name: Build test and analyse Front
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'front'

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
      - name: Cache coverage report
        uses: actions/cache@v3
        with:
          path: front/coverage/bobapp/lcov.info
          key: ${{ runner.os }}-front-lcov-${{ hashFiles('front/coverage/bobapp/lcov.info') }}
          restore-keys: ${{ runner.os }}-front-lcov
      - name: SonarSource Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        with:
          projectBaseDir: front
      - name: SonarQuality
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: front/.scannerwork/report-task.txt
